### ISSUE TITLE
Improve README Documentation

### ISSUE THREAD

**Issue by suryateja-challa** [suryateja-challa/KMeans-Segmentation-from-Scratch#3]
## Issue: Improve README Documentation on K-Means Implementation

**Description:**

The current README lacks detailed information on how the K-Means clustering algorithm is implemented from scratch. This issue is created to enhance the README by providing a comprehensive explanation of the implementation process, including the formulas and equations used.

**Implementation Details:**

To improve the README, we should include the following information:

1. **Introduction to K-Means:** Provide a brief introduction to K-Means clustering, explaining its purpose and how it works.

2. **Algorithm Implementation:** Describe the step-by-step process of implementing K-Means from scratch. This should include:

   - **Initialization:** Explain how initial cluster centroids are selected.
   - **Assignment:** Describe how data points are assigned to clusters based on centroid proximity.
   - **Update:** Explain how cluster centroids are updated based on the assigned data points.
   - **Convergence:** Describe the stopping criteria for the algorithm.

3. **Formulas and Equations:** Include the mathematical formulas used in the algorithm. Please format these equations in Markdown to ensure readability. Here are the equations we need:

   - **Euclidean Distance:** The formula to calculate the Euclidean distance between two points.
   
     ```markdown
     Euclidean Distance (d) = √((x2 - x1)^2 + (y2 - y1)^2)
     ```

   - **Centroid Update:** The formula to update the centroid of a cluster.
   
     ```markdown
     New Centroid (C_new) = (1 / n) * Σ(All Points in Cluster)
     ```

4. **Code Examples:** Include code snippets or pseudocode to illustrate how the algorithm is implemented in code.

**Additional Notes:**

- Please ensure that the equations and code examples are well-documented and easy to understand.
- Use clear and concise language to make the README accessible to developers of all levels.
- Consider including visualizations or diagrams to aid in understanding the algorithm.

Your contributions to improving the README will greatly benefit the project and help users understand the implementation of the K-Means clustering algorithm from scratch. Thank you for your help!

**Comment by Veerhan-glitch** [comment]
Hi there, I will love 2 work on this, pls assign me to it.
thx

**Comment by Veerhan-glitch** [comment]
hey i was working on this and ran into some issues, can u pls clarify them for me:
1) if we open the html file, after choosing the image and k, the program gives the file not found error.
![image](https://github.com/suryateja-challa/KMeans-Segmentation-from-Scratch/assets/83816165/aa1f5ead-752e-45f3-837a-232483891b7c)
![image](https://github.com/suryateja-challa/KMeans-Segmentation-from-Scratch/assets/83816165/07f48366-0157-4dcd-ae52-3e198c963823)

2) if we run the app.py file, after the start of debugger starting, nothing happens

![image](https://github.com/suryateja-challa/KMeans-Segmentation-from-Scratch/assets/83816165/111a39f2-6d5c-4ad5-8fbd-1c8b45b47655)

**Comment by suryateja-challa** [comment]
The `app.py` is still under development. Subsequent changes will be implemented soon. For any preliminary tests, please run `test_app.py` to get understanding about the project.
